#!/bin/bash

curl -X POST http://localhost:8080/player -d '{ "name": "Eric R", "preferred_name": "Eric", "phone": "415-519-6214", "email": "eric.rumer@gmail.com", "ghin_number": "0353408" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Dennis R", "preferred_name": "Dennis", "phone": "650-921-0789", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Doug L", "preferred_name": "Doug", "phone": "650-576-7403", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Kathleen", "preferred_name": "Kathleen", "phone": "000-000-0000", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Barry R", "preferred_name": "Barry", "phone": "415-860-2252", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Edward J", "preferred_name": "Edward", "phone": "650-333-6503", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Johnny U", "preferred_name": "Bacardi", "phone": "510-449-4563", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Tim G", "preferred_name": "Grippi", "phone": "650-773-9412", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Jessie M", "preferred_name": "Jessie", "phone": "650-743-6787", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Frank W", "preferred_name": "Frank", "phone": "650-346-7893", "email": "49frankie@gmail.com", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Jeff H", "preferred_name": "Hart", "phone": "650-766-9500", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Maurie V", "preferred_name": "Maurie", "phone": "", "email": "maurieverbrugge@yahoo.com", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Jeff M", "preferred_name": "Cooler", "phone": "415-235-9745", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Paul F", "preferred_name": "Fitz", "phone": "", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Brent", "preferred_name": "Brentwood", "phone": "", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Jim D", "preferred_name": "Cowboy", "phone": "415-416-2236", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Mark P", "preferred_name": "Whole Foods", "phone": "415-203-8634", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Tom", "preferred_name": "Tom", "phone": "", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Eddie", "preferred_name": "Perv", "phone": "650-302-0143", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "John R", "preferred_name": "Coach", "phone": "", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Bob F", "preferred_name": "Papa Fitz", "phone": "", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Joby R", "preferred_name": "Joby", "phone": "650-504-6217", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Matt", "preferred_name": "Matt", "phone": "", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Neil", "preferred_name": "Neil", "phone": "", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Helen", "preferred_name": "Helen", "phone": "", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Larry S", "preferred_name": "Larry", "phone": "", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Mike B", "preferred_name": "Big Mike", "phone": "650-642-1280", "email": "michael@barkerblue.com", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Mark", "preferred_name": "Boston", "phone": "", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Tim V", "preferred_name": "Valentine", "phone": "", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Jeff G", "preferred_name": "Fireman", "phone": "650-464-0834", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Joe W", "preferred_name": "Joe", "phone": "", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Nate", "preferred_name": "Nate", "phone": "775-350-3268", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Frank M", "preferred_name": "Baby Frank", "phone": "650-483-7214", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Ken", "preferred_name": "Rumer", "phone": "303-526-8357", "email": "kenrumer@gmail.com", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Nick P", "preferred_name": "Papa George", "phone": "", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Dan", "preferred_name": "Dan", "phone": "", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Greg", "preferred_name": "Greg", "phone": "", "email": "", "ghin_number": "" }'
curl -X POST http://localhost:8080/player -d '{ "name": "Greg H", "preferred_name": "Potato Head", "phone": "", "email": "", "ghin_number": "" }'



